//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rdlc_report
{
    using System;
    using System.Collections.Generic;
    
    public partial class vemp
    {
        public int Id { get; set; }
        public int EmpID { get; set; }
        public Nullable<System.DateTime> AtDate { get; set; }
        public Nullable<System.DateTime> Logintime { get; set; }
        public Nullable<System.DateTime> logouttime { get; set; }
        public string LeaveType { get; set; }
        public string Name { get; set; }
    }
}
